version: '3.7'

services:  
  app-server:    
    build: .
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dbserveradmin.mysql.database.azure.com:3306/polling_app?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: dbadmin@dbserveradmin
      SPRING_DATASOURCE_PASSWORD: qwer12#$$
  app-client:
    build: .
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app-server